# Generated by Django 5.1.4 on 2025-02-04 15:21

import ckeditor.fields
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import mangxahois.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('SDT', models.CharField(max_length=10)),
                ('image', models.ImageField(null=True, upload_to='media/nguoidungs/%Y/%m/')),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='media/cover_images/%Y/%m/')),
                ('vaiTro', models.IntegerField(choices=[(1, 'QUANTRIVIEN'), (2, 'GIANGVIEN'), (3, 'CUUSINHVIEN')], default=mangxahois.models.VaiTro['QUANTRIVIEN'])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password_changed', models.BooleanField(default=False)),
                ('manually_unlocked', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tuongTac', models.ManyToManyField(related_name='tuong_tac', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaiDang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieuDe', models.CharField(max_length=255)),
                ('thongTin', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('khoa_binh_luan', models.BooleanField(default=False)),
                ('nguoiDangBai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bài đăng',
            },
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noiDung', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('baiDang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binhluans', to='mangxahois.baidang')),
                ('nguoiBinhLuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bình luận',
            },
        ),
        migrations.CreateModel(
            name='KhaoSat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieuDe', models.CharField(max_length=255)),
                ('moTa', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nguoiTao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Khảo sát',
            },
        ),
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noiDung', models.CharField(max_length=255)),
                ('khaoSat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cauhois', to='mangxahois.khaosat')),
            ],
            options={
                'verbose_name_plural': 'Câu hỏi khảo sát',
            },
        ),
        migrations.CreateModel(
            name='LuaChon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noiDung', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('cauHoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luachons', to='mangxahois.cauhoi')),
            ],
            options={
                'verbose_name_plural': 'Lựa chọn câu hỏi',
            },
        ),
        migrations.CreateModel(
            name='ThongBaoSuKien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieuDe', models.CharField(max_length=255)),
                ('noiDung', ckeditor.fields.RichTextField()),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('nguoiGui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nhomNhan', models.ManyToManyField(related_name='thong_bao_nhan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Thông báo sự kiện',
            },
        ),
        migrations.CreateModel(
            name='ThongKeKhaoSat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_thong_ke', models.DateTimeField(auto_now_add=True)),
                ('khaoSat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangxahois.khaosat', verbose_name='Khảo sát')),
            ],
            options={
                'verbose_name_plural': 'Thống kê khảo sát',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.IntegerField(choices=[(1, 'LIKE'), (2, 'HAHA'), (3, 'LOVE')])),
                ('baiDang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='mangxahois.baidang')),
                ('nguoiThucHien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cảm xúc',
                'unique_together': {('baiDang', 'nguoiThucHien')},
            },
        ),
        migrations.CreateModel(
            name='TraLoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cauHoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangxahois.cauhoi')),
                ('khaoSat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traloi', to='mangxahois.khaosat')),
                ('luaChon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangxahois.luachon')),
                ('nguoiTraLoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trả lời khảo sát',
                'unique_together': {('nguoiTraLoi', 'cauHoi')},
            },
        ),
    ]
